// Generated by CoffeeScript 1.3.3
var Controller;

Controller = (function() {

  function Controller() {
    this.routes = [
      {
        "/workers/keepalive/:id": "/workers/keepalive/:id",
        http_method: "put",
        method: "keep_alive"
      }, {
        "/worker/register": "/worker/register",
        http_method: "post",
        method: "register_worker"
      }, {
        "/employee": "/employee",
        http_method: "get",
        method: "employ_worker"
      }, {
        "/workers": "/workers",
        http_method: "get",
        method: "get_workers"
      }
    ];
    return;
  }

  Controller.prototype.get_workers = function(req, res) {};

  Controller.prototype.keep_alive = function(req, res) {};

  Controller.prototype.employ_worker = function(req, res) {};

  Controller.prototype.register_worker = function(req, res) {};

  return Controller;

})();

module.exports = Controller;
