// Generated by CoffeeScript 1.3.3
var SessionManager;

require('./workermanager');

SessionManager = (function() {
  var Internal, instance;

  function SessionManager() {}

  instance = void 0;

  Internal = (function() {

    function Internal() {
      this.workermanager = WorkerManager();
      return;
    }

    Internal.prototype.start = function(uid) {};

    Internal.prototype.stop = function(uid) {};

    return Internal;

  })();

  SessionManager.get = function() {
    return instance != null ? instance : instance = Internal();
  };

  return SessionManager;

})();

module.exports = SessionManager;
