// Generated by CoffeeScript 1.3.3
var WeiboController;

WeiboController = (function() {

  function WeiboController() {
    this.route = [
      {
        "/weibo/:id/start": "/weibo/:id/start",
        http_method: "put",
        method: "start_work"
      }, {
        "/weibo/:id/stop": "/weibo/:id/stop",
        http_method: "put",
        method: "stop_work"
      }, {
        "/weibo/followers/results/:id": "/weibo/followers/results/:id",
        http_method: "post",
        method: "handle_fl_results"
      }, {
        "/weibo/miniblogs/results/:id": "/weibo/miniblogs/results/:id",
        http_method: "post",
        method: "handle_mb_results"
      }, {
        "/weibo/followers/failure/:id": "/weibo/followers/failure/:id",
        http_method: "post",
        method: "handle_fl_failure"
      }, {
        "/weibo/miniblogs/failure/:id": "/weibo/miniblogs/failure/:id",
        http_method: "post",
        method: "handle_mb_failure"
      }, {
        "/weibo/followers/error/:id": "/weibo/followers/error/:id",
        http_method: "get",
        method: "handle_fl_error"
      }, {
        "/weibo/miniblogs/error/:id": "/weibo/miniblogs/error/:id",
        http_method: "get",
        method: "handle_mb_error"
      }
    ];
    return;
  }

  WeiboController.prototype.start_work = function(req, res) {};

  WeiboController.prototype.stop_work = function(req, res) {};

  WeiboController.prototype.handle_fl_results = function(req, res) {};

  WeiboController.prototype.handle_mb_results = function(req, res) {};

  WeiboController.prototype.handle_fl_failure = function(req, res) {};

  WeiboController.prototype.handle_mb_failure = function(req, res) {};

  WeiboController.prototype.handle_fl_error = function(req, res) {};

  WeiboController.prototype.handle_mb_error = function(req, res) {};

  return WeiboController;

})();
