// Generated by CoffeeScript 1.3.3
var dbConn, dbOne, mongoose,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

mongoose = require('mongoose');

dbOne = (function() {

  function dbOne(uri) {
    this.dburi = uri;
  }

  dbOne.prototype.createConn = function() {
    var conn;
    conn = mongoose.createConnection(uri);
    return conn;
  };

  return dbOne;

})();

dbConn = (function() {
  var Internal, instance;

  function dbConn() {}

  instance = void 0;

  dbConn.getConn = function(uri) {
    if (instance == null) {
      instance = new dbOne();
    }
    return instance.getConn(uri);
  };

  Internal = (function() {

    function Internal() {
      var conn_arr;
      conn_arr = new Array();
    }

    Internal.prototype.getConn = function(uri) {
      var theconn, thedb;
      if (__indexOf.call(conn_arr, uri) >= 0) {
        return conn_arr[uri];
      } else {
        thedb = new dbOne(uri);
        theconn = thedb.createConn();
        conn_arr[uri] = theconn;
        return theconn;
      }
    };

    return Internal;

  })();

  return dbConn;

})();
