// Generated by CoffeeScript 1.3.3
var miniBlog;

miniBlog = (function() {

  function miniBlog() {
    this.miniblog_schema = new Schema({
      mid: {
        type: String
      },
      uid: {},
      timestamp: {},
      imgs: [],
      medias: []
    });
    this.flag_schema = new Schema({
      uid: {},
      maxmid: {}
    });
  }

  miniBlog.prototype.find_blog_by_id = function(id) {};

  miniBlog.prototype.find_blogs_by_uid1 = function(uid, start, num) {};

  miniBlog.prototype.find_blogs_by_uid2 = function(uid, mid, gt) {};

  return miniBlog;

})();

module.exports = miniBlog;
