// Generated by CoffeeScript 1.3.3
var roster;

roster = (function() {

  function roster() {
    var roster_schema;
    roster_schema = new Schema({
      fansnum: {},
      followersnum: {},
      blogsnum: {},
      userphoto: {},
      usertype: {},
      info: {},
      usernick: {},
      userhref: {},
      updatetime: {},
      stamptime: {},
      createtime: {}
    });
  }

  return roster;

})();

module.exports = roster;
